---
title: "Final Report"
author: "U. Ifechi, P. Wittel"
date: "4/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statisticial Analysis of the factors that correlate to Plastic Waste Generation

## Introduction

|   Plastic Waste and plastic pollution is a growing global problem. Current end-of-life processing of plastic are insufficient for dealing with the mass of plastic production in a environmentally sustainable manner. Only a total of XXX % of Plastic ever generated has been recycled since 1955, and today's recycling rate is at XXX %. Incineration is another end-of-life process for plastics, however incinerated plastic contaminate the surrounding air quality, effecting the health of local residents and contributing green house gases. The most common end-of-life process for plastic is disposal, which includes both managed and un-managed disposal. However, most commercial plastics are not naturally degradable and plastic waste that is exposed to UV radiation will break down to micro-plastics which has a negative effect on both environmental health as well as human health. These issues of waste management are compound by the annual increase in the production of plastics each year. Plastic production has increased from XXX % in 1950 to XXX % in 2021. 

|   To address the issue of plastic waste, this study aims to investigate the the historic economical and social factors of political entities in 2010 that contributed to the generation of plastic waste generated in 2010. Entities in this case are recognized semi-independent political structures; examples include nation states, city-states, and overseas territories. 

## Methodology

|   Data was pull from open-sourced data bases, such as (INCLUDE EXAMPLES HERE), therefore The scope of this investigation was limited to the data that was available to us. We pulled plastic generation and plastic waste from our _our world in data_ and economic and social metrics such as GDP, population, economic growth, and wealth disparage. We explored several machine-learning methods, including supervised and un-supervised methods, using the imputed data and investigated different metrics to compare the models created. 

|   The purpose of this model is explanation, therefore we do not need to use a typical 70:30 split of the data for a training dataset and a testing dataset. However to ensure that the models made are not prone to over-fitting the available data, we used the most through cross-validation method available to us, LOOCV. This ensures that the final model does not overfit to high-impact data points. We were able to make several supervised models that could give use the relationship of each factor to the tonnage of plastic waste generated. Using the unsupervised learning methods we could not find correlations between the factors and the response, but we were able to find groups that share common elements. Using these groups we are able to see which factors are grouping entities together, and see how much tonnage of plastic waste was generated for each group.

## Data Cleaning

### Missing Data

|   The compiled dataset had a high amount of missing values; very few observation had values for every factor. Out of 244 observations 76 observations (31.1%) were missing the response value: 'Plastic waste generation in tonnes'. A complied list of all the proportion of missing values for each variable form the complied dataset is shown in (FIGURE: table of NA's by factor). To cut out observation that had missing values would have reduced the dataset by too much to make a statistically meaningful analysis. Thus, to preserve as much data as possible we explored several methods of imputation. Random-Forest imputation was used as well as Predictive mean match.

`r NA_table`

|   There was concern about data that showed Informed missing; entities with smaller GPD were more likely to have missing data about plastic waste generation. However, since the alternative is forgoing any analysis we preceded with the imputation but remained mindful of possible short-comings of the analysis due to the possibility of informed missing data.



## Results


## Conclution


## Apendix








