---
title: "Gathering Data"
author: "Ifechi Umeh"
date: "3/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

```{r}
waste_total <- read_csv("Data Raw/plastic-waste-generation-total.csv")

waste_per_cap <- read_csv("Data Raw/plastic-waste-per-capita.csv")
waste_per_cap <-  waste_per_cap %>% 
                    select(c("Entity", "Per capita plastic waste (kg/person/day)"))

waste_totgbl_mismanage <- read_csv("Data Raw/mismanaged-waste-global-total.csv")
waste_totgbl_mismanage <-  waste_totgbl_mismanage %>% 
                             select(c("Entity", "Mismanaged waste (% global total)"))

waste_inadequate_manage <- read_csv("Data Raw/inadequately-managed-plastic.csv")
waste_inadequate_manage <-  waste_inadequate_manage %>% 
                              select(c("Entity", "Share of plastic inadequately managed"))
```

```{r}
webpage <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_population_in_2010")

pop <- html_table(webpage, fill = TRUE)
```

Note: A lot of the N/a's in the wiki webpage are smaller Islands nations/ territories. I would be a little uncomfortable with imputing this data since it is Informed Missing. I found that we could find some of those missing values

```{r}
country_pop <- pop[[2]]

names(country_pop) <- c("Rank", "Entity",
                      "Population_2010", "Chng_2005",
                      "Area_km2", "Popdens")

country_pop <- country_pop %>% 
  filter(Entity != "World")

country_pop$Population_2010 <- 
  as.numeric(str_remove_all(country_pop$Population_2010, ","))

country_pop$Area_km2 <- 
  as.numeric(str_remove_all(country_pop$Area_km2, ","))

country_pop <- country_pop %>% 
                 select(c("Entity", "Population_2010", "Area_km2"))
```

```{r}
country_gdp <- read_csv("Data Raw/Country-GPD-per-capita.csv")
country_gdp$`GDP per capita, current prices (U.S. dollars per capita)`
country_gdp <- country_gdp %>% 
                 select(c("GDP per capita~", "2010"))

#alt way (I am not sure what libary you were using so I had to write my own code)
country_gdp_capita <- country_gdp %>% transmute(Entity = `GDP per capita, current prices
 (U.S. dollars per capita)`,
 gdp_per_capita = `2010`)

```


```{r}
gdp_country <- read_csv("Data Raw/World Bank GDP data/World bank gdp.csv") 

gdp_country <- gdp_country %>% 
  select(`Country Name`, `2010`) %>% 
  rename("Entity" = `Country Name`,
         "GPD (in USD 2015)" = `2010`)

```

```{r}
tab1 <- full_join(waste_total, country_pop, by = "Entity")
tab2 <- full_join(tab1, waste_per_cap, by = "Entity")
tab3 <- full_join(tab2, waste_totgbl_mismanage, by = "Entity")
tab4 <- full_join(tab3, waste_inadequate_manage, by = "Entity")
tab5 <- left_join(tab4, gdp_country, by = "Entity")
#tab6 <- left_join(tab5, country_gdp_capita, by = "Entity") not sure what year is the USD in.
```

```{r}
write_csv(tab5, "Data Clean/master_table.csv")

```


Fuel Subsidies
```{r}
fuel_sub <- read_csv("Data Raw/fossil-fuel-subsidies-gdp.csv") 

fuel_sub <- fuel_sub %>% 
  mutate('Fossil-Fuel subsities as proportion of total GDP' = fuel_sub$`12.c.1 - Fossil-fuel subsidies (consumption and production) as a proportion of total GDP (%) - ER_FFS_CMPT_GDP`) %>% 
  filter(Year == 2015) %>% 
  filter(!is.na(Code)) %>% 
  select(Entity, `Fossil-Fuel subsities as proportion of total GDP`, Code)


tab7 <- left_join(tab5, fuel_sub, by = "Entity")

write_csv(tab7, "Data Clean/master_Table_Fuel.csv")

```





